CREATE DATABASE TPC;
USE TPC;

CREATE TABLE Db_Room (
Name_Room VARCHAR(100),
Code_Room INTEGER PRIMARY KEY,
Started_Game BOOLEAN);

CREATE TABLE Db_Basic (
Id_Basic INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
Nick_Heritage VARCHAR(100),
Question VARCHAR(400),
Right_Answer VARCHAR(400),
Wrong_Answer_One VARCHAR(400),
Wrong_Answer_Two VARCHAR(400),
Wrong_Answer_Three VARCHAR(400),
Tip_One VARCHAR(400),
Tip_Two VARCHAR(400),
Tip_Three VARCHAR(400),
Position INTEGER,
foto LONGBLOB,
Code_Room INTEGER,
FOREIGN KEY (Code_Room) REFERENCES Db_Room(Code_Room));
